<Project>
    <!-- NuGet Metadata -->
    <PropertyGroup>
        <PackageProjectUrl>https://fable.io</PackageProjectUrl>
        <RepositoryUrl>https://github.com/fable-compiler/fable-promise</RepositoryUrl>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Description>Promise API and computation expression for Fable</Description>
        <PackageIcon>fable_logo.png</PackageIcon>
        <PackageTags>fsharp;fable;javascript;f#;js;fable-javascript</PackageTags>
        <Authors>Fable contributors</Authors>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <!-- For SourceLink. See: https://github.com/dotnet/sourcelink#using-source-link-in-net-projects -->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>
    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)\fable_logo.png" Pack="true" Visible="false" PackagePath="" />
        <None Include="$(MSBuildThisFileDirectory)\LICENSE" Visible="false" Pack="true" PackagePath="" />
        <None Include="$(MSBuildThisFileDirectory)\README.md" Visible="false" Pack="true" PackagePath="" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
    </ItemGroup>
</Project>
