<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Prelude.fs" />
    <Compile Include="PromiseTests.fs" />
    <Compile Include="PromiseLikeTests.fs" />
    <Compile Include="AsyncIterableTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Scriptorium.Nib" Version="0.4.1" />
    <PackageReference Include="Scriptorium.Quill" Version="0.7.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\Fable.Promise.fsproj" />
  </ItemGroup>
</Project>
