<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <FablePackageType>library</FablePackageType>
    <ChangelogFile>$(MSBuildThisFileDirectory)../CHANGELOG.md</ChangelogFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Promise.fs" />
    <Compile Include="PromiseImpl.fs" />
    <Compile Include="AsyncIterable.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="5.2.0" />
    <PackageReference Include="EasyBuild.PackageReleaseNotes.Tasks" Version="2.1.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Fable.Package.SDK" Version="1.4.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Update="FSharp.Core" Version="4.7.2" />
  </ItemGroup>
</Project>
